# Generated by Django 4.2.5 on 2023-10-02 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_cration_date_todo_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='duedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 10, 2, 16, 45, 11, 916123)),
        ),
    ]
